# Kubernetes Secret for Frontend
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  labels:
    app: connectsphere-frontend
  namespace: default
stringData:
  NEXT_PUBLIC_API_URL: http://connectsphere.local/api
